package su.nightexpress.quantumrpg.types;

public enum ActionType {
  BUFF, EFFECT, POTION, COMMAND, PLAYER_COMMAND, OP_COMMAND, TELEPORT, BROADCAST, MESSAGE, ACTION_BAR, TITLES, SOUND, ARROW, FIREBALL, WITHER_SKULL, IGNITE, DELAY, ANIM_DELAY, LIGHTNING, FIREWORK, THROW, HOOK, PARTICLE_LINE, PARTICLE_PULSE, DAMAGE, SPELL, MYTHIC_SKILL;
}
