command-aliases: consumables,consumes
auto-update: false
auto-update-override-changes: false
consuming:
  allow-on-full-health: true
  allow-on-full-food: true
item-format:
  name: '%ITEM_NAME%'
  lore:
    - '%ITEM_LORE%'
